const MockList = {
  cargoList: [
    'Computer',
    'Electronic',
    'Vegetable',
    'Kid toys',
    'Steel',
    'Coffee',
    'Tea',
    'Headphone',
    'Smartphone',
    'Clothes',
    'Liquid',
    'Milk',
    'Seafood',
    'Drug',
    'Weed',
    'Heroin',
    'Ice-cream',
    'Fresh Water'
  ],
  driverList: [
    'Thomas Simson',
    'Newton',
    'Beethoven',
    'Einstein',
    'Donal Trump',
    'Obama',
    'Harry Porter',
    'Bin Clinton',
    'Hillary Rodham Clinton',
    'Super man',
    'Washington',
    'Richard Nixon',
    'J.Kenedy',
    'Abraham Lincoln',
    'Lucky Luke',
    'Michael Jackson',
    'Gerald Ford',
    'Honda',
    'Suzuki',
    'Toyota',
    'David Beckham'
  ]
};
export default MockList;
